#
# Fastfile
# Smartlane
# Copyright (c) 2017 Smart&Soft. All rights reserved.
#
################################################################################

import 'Smartfile'

platform :android do
  def before_task; end

  def after_task
    smartdistrib
    dispenser
    #play_store(track: 'internal')
  end

end
