#
# Fastfile
# Smartlane
# Copyright (c) 2017 Smart&Soft. All rights reserved.
#
################################################################################

import 'Smartfile'

platform :android do
  def before_task; end

  def after_task
    dispenser
    smartdistrib
  end

end
